### PR TITLE
Add a trailing semicolon for the desktop entry in Polish translation

### PR DESCRIPTION
**Pull request by ryonakano**
Fixes the CI fails in the latest master, as per [the CI warns](https://travis-ci.com/kmal-kenneth/monilet/builds/143919906):

```
com.github.kmal-kenneth.monilet.desktop: error: value "Monitor;Wid?et" for locale string list key "Keywords[pl]" in group "Desktop Entry" does not have a semicolon (';') as trailing character
```

### CODE REVIEW

**Comment by kmalkenneth** [comment]
I already tried and it didn't work.  But I will try again.

**Comment by kmalkenneth** [comment]
> com.github.kmal-kenneth.monilet.desktop: error: value "Monitor;Wid?et" for locale string list key "Keywords[pl]" in group "Desktop Entry" does not have a semicolon (';') as trailing character

The error still persists.The error still persists.

**Comment by ryonakano** [comment]
Hmm, really strange :thinking:

**Comment by kmalkenneth** [comment]
@ryonakano @NathanBnm 

When run

```
ninja com.github.kmal-kenneth.monilet-pot
```

It does not generate the **extra.pot** file.

But meson accesses the **po/extra** folder.

Any ideas?

**Comment by NathanBnm** [comment]
You have to run both

```
ninja com.github.kmal-kenneth.monilet-update-po
```

and

```
ninja extra-update-po
```

Using the `-update-po` option instead of just using `-pot` will automatically generate the `.pot` files and update the `.po` files listed in `LINGUAS`.

This should fix the persisting error.

**Review by NathanBnm — APPROVED** [review]

**Comment by ryonakano** [comment]
@NathanBnm Not `-update-pot` but `-update-po`?

**Comment by NathanBnm** [comment]
@ryonakano thanks I just edited it.

**Comment by kmalkenneth** [comment]
@ryonakano @NathanBnm

Thank you very much, I am very grateful to you.

Now I understand that I must use the assigned name.  For translations.

Although it is still not clear to me, how the problem was solved.

If you can check and explain, they help me a lot.

If I can help you with something, I do it with pleasure, if it is within my reach.

**Comment by NathanBnm** [comment]
All of this was because a missing semicolon. We just had to add it and update the translation files like I described above.
But it's not an easy thing to see that a semicolon is missing.

**Comment by kmalkenneth** [comment]
Interestingly, I corrected the entire Polish translation.  Adding the semicolon.

But it still doesn't work.

I even removed all the Polish translation and the error persisted.

I think there was something else.

When I set for a new version it started working.

I don't know how this affects travis.

But the other commits added after that work correctly.

**Comment by NathanBnm** [comment]
That's strange. I really don't know then.

**Pull request closed without merging**
