### PR TITLE
Fix appdata.xml

### PR DESCRIPTION
**Pull request by NathanBnm**
There was some issues with the appdata file. I hope this PR will fix the build.

Also I noticed that you doesn't mention OARS information in your appdata.xml file. This is required in order to publish you app in the AppCenter.

You just have to complete the following lines I added to your file. Default is none. You can identify what you have to change in the following lines here https://hughsie.github.io/oars/generate.html :wink:

Let me know if you have questions before merging.

**This PR is ready for review**

### CODE REVIEW

**Comment by NathanBnm** [comment]
@ryonakano sorry for bothering you, but do you have an idea about this? I can't figure out why is the build failing.

**Comment by kmalkenneth** [comment]
@NathanBnm I think it has to do with the translation of the .desktop file.

I will check later.

**Comment by NathanBnm** [comment]
> @NathanBnm I think it has to do with the translation of the .desktop file.
> 

I don't see how. I checked the files and I cannot find a solution.

**Comment by kmalkenneth** [comment]
I saw that one semicolon was missing in the Polish translation.

The translation was deleted and still generates the same error.  I do not understand what happens.

**Comment by kmal-kenneth** [comment]
The translation was deleted and still generates the same error.  I do not understand what happens.

**Comment by ryonakano** [comment]
I've made a PR that should fix building: #25.

**Pull request merged**
