### PR TITLE
Remove non-working validation tests

### PR DESCRIPTION
**Pull request by NathanBnm**
There's still an issue. You have to remove validation tests for now.

### CODE REVIEW

**Comment by kmalkenneth** [comment]
I see many changes, but I don't understand why.

I appreciate your help, but I would like to know more about the changes. ... excuse my ignorance.

I must clarify I am a newbie.

Thank you.

**Comment by NathanBnm** [comment]
Not a problem. Do not hesitate to ask!

These validation tests are deprecated. They're not working correctly anymore since the Houston CI script has been updated (The script launched by Travis CI).

**Comment by NathanBnm** [comment]
As you can see the build is still failing. I'm going to search for the issue.
But this confirms that the validation tests are launched by Houston CI without need to ask them to launch.

**Comment by kmalkenneth** [comment]
Effectively.
I apologized but I must do something else, then I will check how everything goes.
Thank you.

**Pull request merged**
